name: 'simple'
version: 0.0.1
description: >
  An absolute bare-bones web app.

#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

  m4d_components: '>=0.1.29 <2.0.0'
    # git:
    #  url: git@github.com:MikeMitterer/dart-material-design-lite.git
    #  ref: v2.2

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  sass_builder: any


